import { ChatAction } from './config.ts';

// Re-export configuration types for external use
export type {
  ChatAction,
  GuideLanguage,
  DetailLevel,
  ActionQueryConfig,
  StyleGuideChatExtendedConfig,
} from './config.ts';

// Re-export constants for frontend reference
export {
  VALID_ACTIONS,
  VALID_GUIDE_LANGUAGES,
  DEFAULT_GUIDE_LANGUAGE,
  DEFAULT_DETAIL_LEVEL,
  DEFAULT_INCLUDE_EXAMPLES,
} from './config.ts';

// =============================================================================
// TWO-PHASE GENERATION TYPES
// =============================================================================

/**
 * Generation phase for the two-phase style guide creation workflow.
 * - 'proposal': AI generates a structured outline for user review
 * - 'final': AI generates the full document based on confirmed outline
 */
export type GenerationPhase = 'proposal' | 'final';

/**
 * Valid generation phases for validation
 */
export const VALID_GENERATION_PHASES: GenerationPhase[] = ['proposal', 'final'];

/**
 * A subsection within a proposed outline section
 */
export interface ProposedSubsection {
  /** Unique identifier for the subsection */
  id: string;
  /** Subsection title */
  title: string;
  /** Brief description of what this subsection covers */
  description: string;
}

/**
 * A section within the proposed outline.
 * Each section represents a major topic area in the style guide.
 */
export interface ProposedSection {
  /** Unique identifier for the section (e.g., "naming-conventions") */
  id: string;
  /** Section title (e.g., "Naming Conventions") */
  title: string;
  /** Brief description of what rules/guidelines this section covers */
  description: string;
  /** List of subsections/sub-topics within this section */
  subsections: ProposedSubsection[];
  /** Whether this section is included in the final generation (default: true) */
  included: boolean;
  /** Optional user notes/preferences for this section */
  notes?: string;
}

/**
 * The proposed outline generated by the AI during the proposal phase.
 * Contains the full structure of the style guide before final generation.
 */
export interface ProposedOutline {
  /** Suggested document title */
  title: string;
  /** Suggested category for the style guide */
  category: string;
  /** Ordered list of proposed sections */
  sections: ProposedSection[];
}

// =============================================================================
// CORE TYPES
// =============================================================================

/**
 * Style guide summary for context building
 */
export interface StyleGuideSummary {
  id: string;
  name: string;
  category: string;
  content: string;
}

/**
 * Request body for chat-style-guide Edge Function
 */
export interface ChatStyleGuideRequest {
  /** User message to process */
  message: string;
  /** Action type: query, suggest, generate, or modify */
  action: ChatAction;
  /** Project ID for context and tracking */
  project_id: string;
  /** Optional user ID for tracking */
  user_id?: string;
  /** Optional conversation ID for continuity */
  conversation_id?: string;
  /** Optional target guide ID for modify action */
  target_guide_id?: string;
  /** Optional custom system prompt override */
  system_prompt?: string;
  /** Optional custom user prompt override */
  user_prompt?: string;
  /** Optional previous response ID for conversation continuity */
  previous_response_id?: string;
  /** Optional model override */
  model?: string;
  /** Optional temperature override */
  temperature?: number;
  /** Optional token limit override */
  token_limit?: number;
  /**
   * Generation phase for two-phase workflow.
   * - 'proposal': Generate a structured outline for review (default for 'generate' action)
   * - 'final': Generate the full document based on confirmed outline
   * When omitted for 'generate' action, defaults to 'proposal'.
   */
  generation_phase?: GenerationPhase;
  /**
   * Confirmed outline from the proposal phase.
   * Required when generation_phase is 'final'.
   * Sections with included=false will be skipped in the final generation.
   */
  confirmed_outline?: ProposedOutline;
}

/**
 * Action required in response
 */
export type ActionRequired = 'none' | 'confirm_create' | 'confirm_update' | 'review_outline';

/**
 * Metadata about the chat response
 */
export interface ChatMetadata {
  /** IDs of style guides used in the response */
  sources_used: string[];
  /** Token usage information */
  token_usage?: {
    input_tokens: number;
    output_tokens: number;
    total_tokens: number;
  };
  /** Action type processed */
  action_processed: ChatAction;
  /** Processing time in milliseconds */
  processing_time_ms?: number;
  /** Generation phase that was processed */
  generation_phase?: GenerationPhase;
}

/**
 * Response data for chat-style-guide Edge Function
 */
export interface ChatStyleGuideResponse {
  /** Operation success status */
  success: boolean;
  /** AI response text */
  response?: string;
  /** Conversation ID for continuity */
  conversation_id?: string;
  /** Suggested content when generating or modifying */
  suggested_content?: string;
  /** Suggested name for the style guide (extracted from content or AI response) */
  suggested_name?: string;
  /** Suggested category for the style guide */
  suggested_category?: string;
  /** Action required from user */
  action_required: ActionRequired;
  /** Response metadata */
  metadata?: ChatMetadata;
  /** Error message if failed */
  error?: string;
  /**
   * Proposed outline from the proposal phase.
   * Present when generation_phase was 'proposal' and AI successfully generated an outline.
   */
  proposed_outline?: ProposedOutline;
}

/**
 * Validation result for request body
 */
export interface ValidationResult {
  valid: boolean;
  error?: string;
}
